language: node_js
node_js:
  - 12
cache:
  directories:
    - "node_modules"
env:
  global:
    - COVERALLS_PARALLEL=true
jobs:
  include:
    - stage: Produce Coverage
      node_js: node
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage